name: baby_stats

services:
  db:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_DB: baby_stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
