name: baby_stats

services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES__DATABASE}
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    ports:
      - "${POSTGRES__PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER__PORT}:8080"
    depends_on:
      - db

volumes:
  postgres_data:
